# Generated by Django 6.0.1 on 2026-02-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
