# Generated by Django 6.0.1 on 2026-02-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_producto_color_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(choices=[('negro', 'Negro'), ('blanco', 'Blanco'), ('gris', 'Gris'), ('Azul', 'Azul'), ('Rojo', 'Rojo'), ('verde', 'Verde'), ('beige', 'Beige'), ('amarillo', 'Amarillo')], max_length=40, null=True),
        ),
    ]
