# Generated by Django 6.0.1 on 2026-02-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_producto_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(choices=[('negro', 'Negro'), ('blanco', 'Blanco'), ('gris', 'Gris'), ('Azul', 'Azul'), ('Rojo', 'Rojo'), ('verde', 'Verde'), ('beige', 'Beige'), ('amarillo', 'Amarillo'), ('otros', 'Otros')], max_length=40, null=True),
        ),
    ]
