# Generated by Django 6.0.1 on 2026-02-02 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_remove_producto_stock_alter_producto_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='productos/principales/', verbose_name='Imagen principal'),
        ),
        migrations.AddField(
            model_name='producto',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/%Y/%m/%d/', verbose_name='Archivo de imagen')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Número que determina el orden de las imágenes (menor = primero)', verbose_name='Orden de visualización')),
                ('is_principal', models.BooleanField(default=False, help_text='Marcar si esta es la imagen principal del producto', verbose_name='¿Es imagen principal?')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción de la imagen para SEO y accesibilidad', max_length=200, null=True, verbose_name='Descripción (alt text)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ventas.producto', verbose_name='Producto asociado')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['orden', 'created_at'],
                'unique_together': {('producto', 'orden')},
            },
        ),
    ]
