# Generated by Django 6.0.1 on 2026-02-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_remove_producto_imagen_producto_imagen_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento_porcentaje',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de descuento (0-100)', verbose_name='Descuento (%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_fin_oferta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de oferta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_inicio_oferta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio de oferta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='is_oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio antes del descuento (opcional)', max_digits=10, null=True, verbose_name='Precio original'),
        ),
    ]
