# Generated by Django 6.0.1 on 2026-02-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_producto_descuento_porcentaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(choices=[('negro', 'Negro'), ('blanco', 'Blanco'), ('gris', 'Gris'), ('azul', 'Azul'), ('rojo', 'Rojo'), ('verde', 'Verde'), ('beige', 'Beige'), ('amarillo', 'Amarillo'), ('otros', 'Otros')], max_length=40, null=True),
        ),
    ]
