# Generated by Django 6.0.1 on 2026-02-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_alter_producto_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imagenproducto',
            unique_together=set(),
        ),
    ]
